myinfo/urls.py
from django.urls import path
from . import views

app_name = 'myinfo'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('create/', views.CreateView.as_view(), name='create'),
    # path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('add_post', views.add_post, name='add_post'),   # インラインフォームセット
    # path('<int:pk>/update/', views.update_post, name='update_post'),

    path("formview_test", views.aaa.as_view(), name="formview_test"),

    path('export/', views.post_export, name='export'),

    # path('create_comment', views.create_comment, name='create_comment'),   # コメントポスト

    path('fileuptest', views.upload_file, name='fileuptest'),#`ファイルUPテスト用`

    path('', views.information_list, name='index'),   # FBVで一覧
    path('add_fbvform', views.add_fbvform, name='add_fbvform'),   # FBVでCreate
    path('<int:pk>/', views.detail_fbvform, name='detail'),# FBVでDetail
    path('<int:pk>/update/', views.edit_fbvform, name='update'),# FBVでUpdate

    #通知削除関数呼び出し
    path('notifi_delete', views.notifi_delete, name='notifi_delete'),
    
    #添付ファイル削除関数呼び出し
    path('<int:pk>/attach_delete', views.attach_delete, name='attach_delete'),

    # #コメント投稿
    # path('<int:pk>/comment_post', views.comment_post, name='comment_post'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('summernote/', include('django_summernote.urls')),

    path('myinfo/', include('myinfo.urls')),
    path('', RedirectView.as_view(url='/myinfo/')),

]


#     """ 開発環境下のみ設定 """
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myinfo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import os

#添付ファイル
from django.core.validators import FileExtensionValidator


from django.conf import settings
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class InfoCategory(models.Model):
    name = models.CharField(max_length=100, null=True, verbose_name="カテゴリ名")
    sort_no = models.IntegerField(verbose_name="ソートNo")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "カテゴリ"


# Informationクラス
class Information(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(InfoCategory, null=True, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    body = models.TextField()
    to_flag = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
     
    def __str__(self):
        # return self.title
        return f"{self.category} {self.title}"

    class Meta:
        verbose_name_plural = "お知らせ"




    def get_absolute_url(self):
        return reverse('myinfo:detail', kwargs={'pk':self.pk})

class ReadStates(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    information = models.ForeignKey(Information, on_delete=models.CASCADE, related_name='info_read')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name_plural = "既読"


class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    information = models.ForeignKey(Information, on_delete=models.CASCADE, related_name='info_notifi')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # return self.user
        return str(self.user)

    class Meta:
        verbose_name_plural = "通知"


class InfoComments(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    information = models.ForeignKey(Information, on_delete=models.CASCADE)
    #commentはSQL競合のためバッククオートでくくる？
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment[:20]#開始20文字

    class Meta:
        verbose_name_plural = "コメント"


class Attachments(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    file_path = models.FileField(
        upload_to = 'uploads/%Y/%m/%d/',
        # verbose_name = 'attached file',
        # validators=[FileExtensionValidator(['jpg', ])],
        null = True
    )
    
    information = models.ForeignKey(
        Information, verbose_name='紐づくお知らせ',
        blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='info_attach',
    )

    # def __str__(self):
    #     return self.name

    """ -----file_name属性として作成----- """
    def file_name(self):
        path = os.path.basename(self.file_path.name)  # ファイル名のみ抽出
        return path

    class Meta:
        verbose_name_plural = "添付ファイル"

myinfo/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect
from django.http import HttpResponse, Http404 # 追記

from django.views import generic
from .models import Information, InfoCategory, Attachments, Notifications, ReadStates, InfoComments
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from .forms import InformationForm, FileFormset, InfoCommentsForm, InformationEditForm

from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


#関数ビューで通知の中間テーブルCreateを作ってみる
def add_fbvform(request):
    if request.method == "POST":
        form = InformationForm(request.POST, request.FILES)

        if form.is_valid(): 
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()

            #添付ファイル：保存＆モデル書き込み
            # pdf_files = request.FILES.getlist()
            # for pdf in pdf_files:
            if 'pdf_file1' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file1'] , information=obj)
                instance.save()

            if 'pdf_file2' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file2'] , information=obj)
                instance.save()

            if 'pdf_file3' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file3'] , information=obj)
                instance.save()


            # code    = request.POST["code"]
            # city    = request.POST["city"]
            # A       = Airport(code=code, city=city) #インスタンス作成
            # A.save()  #データベースに保存

            # user = get_object_or_404(User, pk=request.POST["notification_user"])#これで出来た
            # user = User.objects.get(pk=request.POST["notification_user"])
            # Notifications.objects.create(user=user, information=obj)

            #通知：選択したユーザー
            result = request.POST.getlist("tags")
            for user in result:
                # user_instance = User.objects.get(pk=user)#これ出来ない・
                user_instance = get_object_or_404(User, pk=user)
                Notifications.objects.create(user=user_instance, information=obj)
                #既読も同じでok？
                ReadStates.objects.create(user=user_instance, information=obj)

            # if request.FILES['file']:
            #     for excel in request.FILES.getlist('excel'):
            
                # files = request.FILES.getlist('file', False)

            # if file in request.files:
            #     files = request.FILES.getlist('file')

            # if request.method == 'POST' and request.FILES['myfile']:
            #     myfile = request.FILES['myfile']
            #     fs = FileSystemStorage()
            #     filename = fs.save(myfile.name, myfile)
            #     uploaded_file_url = fs.url(filename)

            #↓これ↓が最終
            # file = request.FILES.get('file')
            # Attachments.objects.create(file_path=file, information=obj)
            #↓これ↑が最終

                # for file in files:
                #     Attachments.objects.create(file_path=file, information=obj)


            return redirect('myinfo:index')

    else:
        form = InformationForm  

        #ここに

    return render(request, 'myinfo/add_fbvform.html', {'form': form })


#Detail関数ビュー
def detail_fbvform(request, pk):
    template_name = "myinfo/information_detail.html"

    try:
        information = Information.objects.get(pk=pk)
    except Information.DoesNotExist:
        raise Http404("Information does not exist")

    #コメント入力時
    if request.method == 'POST':
        # form = InfoCommentsForm(request.POST)  # POSTデータをフォームに保存する→これ出来ない
        # if form.is_valid():
        #     comment_obj = form.save(commit=False)
        #     comment_obj.user = request.user
        #     comment_obj.information = information
        #     comment_obj.save()

        # 投稿されたコメントをデータベースに保存
        if request.POST["text"] != "":
            InfoComments.objects.create(
                comment=request.POST["text"],
                information=information,
                user = request.user
                )
        else:
            messages.warning(request, 'コメント欄は未入力です')

    
    #通知表示用（有無だけ）
    if request.user.id is not None:
        notifi_exis =  Notifications.objects.filter(user=request.user).exists()

        context = {
            "information":information,
            'notifi_exis':notifi_exis,
        }

        #既読にする（中間テーブルから削除する）
        read_exis = ReadStates.objects.filter(user=request.user, information=pk).exists()
        if read_exis == True:
            ReadStates.objects.filter(user=request.user, information=pk).delete()

    else:
        context = {
            "information":information,
        }



    return render(request,template_name,context)


#Update関数ビューつくる
def edit_fbvform(request, pk, *args, **kwargs):

    information = get_object_or_404(Information, pk=pk)

    #添付と通知と既読を取得
    # attachments = Attachments.objects.filter(information_id__exact=pk).all()
    # notifications = Notifications.objects.filter(information_id__exact=pk).all()
    # readStates = ReadStates.objects.filter(information_id__exact=pk).all()

    #外部キーなので_set.all()でなくrelated_nameで
    attachments = information.info_attach.all()
    notifications = information.info_notifi.all()
    read_states = information.info_read.all()

    # unread_member = read_states.values_list('user', flat=True)
    # notifi_member = notifications.values_list('user', flat=True)
    # # read_member = notifi_member.difference(unread_member)

    # read_lst = []


    
    if request.method == 'POST':
        form = InformationEditForm(request.POST, request.FILES, instance=information)

        if form.is_valid(): 
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()

            #添付ファイル3つ
            if 'pdf_file1' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file1'] , information=obj)
                instance.save()
            if 'pdf_file2' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file2'] , information=obj)
                instance.save()
            if 'pdf_file3' in request.FILES:
                instance = Attachments(file_path=request.FILES['pdf_file3'] , information=obj)
                instance.save()

            #通知：選択したユーザー
            result = request.POST.getlist("tags")
            for user in result:
                # user_instance = User.objects.get(pk=user)#これ出来ない・
                user_instance = get_object_or_404(User, pk=user)
                Notifications.objects.get_or_create(user=user_instance, information=obj)
                #既読も
                ReadStates.objects.get_or_create(user=user_instance, information=obj)


            request.session['form_data'] = request.POST

            messages.success(request, '更新しました！')
            return redirect('myinfo:detail', pk=pk)

    else:
    # 一覧表示からの遷移や、確認画面から戻った時

        # # セッションにデータがあればそれを使う →tagsリスト入れてとforms.errorが出る
        # if 'form_data' in request.session:
        #     form = InformationEditForm(request.session.get('form_data'))
        # else:
        #     form = InformationEditForm(instance=information)

        form = InformationEditForm(instance=information)

        context ={
            'form': form,
            'information':information,
            'notification':notifications,
            'attachment':attachments,
            'read_state':read_states,
            
        }

    return render(request, 'myinfo/edit_fbvform.html', context)
    



#インラインフォームセットでattachmentモデルに登録
def add_post(request):
    form = InformationForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        formset = FileFormset(request.POST, files=request.FILES, instance=post)  # 今回はファイルなのでrequest.FILESが必要
        if formset.is_valid():
            post.save()
            formset.save()
            messages.success(request, '登録しました！')
            return redirect('myinfo:index')

        # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
        else:
            context['formset'] = formset

    # GETのとき
    else:
        # 空のformsetをテンプレートへ渡す
        context['formset'] = FileFormset()

    return render(request, 'myinfo/add_postform.html', context)


#インラインフォームセットのUpdateView
def update_post(request, pk):
    post = get_object_or_404(Information, pk=pk)
    form = InformationForm(request.POST or None, instance=post)
    formset = FileFormset(request.POST or None, files=request.FILES or None, instance=post)
    if request.method == 'POST' and form.is_valid() and formset.is_valid():
        form.save()
        formset.save()
        messages.success(request, '更新しました！')
        # 編集ページを再度表示→DeatalViewにした
        # return redirect('myinfo:update_post', pk=pk)
        return redirect('myinfo:detail', pk=pk)

    context = {
        'form': form,
        'formset': formset
    }

    return render(request, 'myinfo/update_postform.html', context)


#未使用のindex
class IndexView(generic.ListView):
    model = Information
    paginate_by = 3

    def get_queryset(self):
        return Information.objects.order_by('-created_at')

#使用中のidndex
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import SearchForm
from django.db.models import Q
def information_list(request):

    #検索
    #検索結果をページネーションするにはSessionから条件取得？
    #→中止して、検索の場合、ページネーションなしにしよう。  
    searchForm = SearchForm(request.GET)

    context = {
        'searchForm': searchForm,
    }

    if searchForm.is_valid():
        # informations = Information.objects.filter(title__contains=keyword).order_by('-id')#ひとまずタイトルに含む
        # タイトルor本文に含む（複数ワード、区切りは半角でも全角スペースでもOK

myinfo/templates/myinfo/add_postform.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block content %}
    <h1 class="h3 text-gray-800 flex-grow-1">おしらせの{{ object|yesno:'更新,作成'}}</h1>

    <form method="POST" enctype="multipart/form-data" action="{% url 'myinfo:add_post' %}" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        <h2>添付ファイル</h2>
        {{ formset.management_form }}
        {% for file_form in formset %}
            {{ file_form.as_p }}
            <hr>
        {% endfor %}

        <div class="btn-toolbar">
            <div class="btn-group">
                <a href='JavaScript:history.back()' class="mx-5 btn btn-secondary">
                <i class="fas fa-chevron-left"></i> 戻る</a>
            </div>

            <div class="btn-group ml-auto" margin-left=auto;>
            <button type="submit" class="submit btn btn-primary">
            <i class="fas fa-check"></i> {{ object|yesno:'更新する（元に戻せません）,作成'}}</button>
            </div>
        </div>
    </form>

    <div>
        
    </div>
{% endblock %}

myinfo/templates/myinfo/information_detail.html
{% extends 'layout.html' %}
{% block content %}

{% if messages %}
		{% for message in messages %}
			<div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
		{% endfor %}
{% endif %}

    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <div class="font-weight-bold text-primary lead">{{ information.title }}</div>

            {% if request.user.id == information.user.id %}
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">action:</div>
                        <a class="dropdown-item" href="{% url 'myinfo:update' information.pk %}">
                        {% comment %} <a class="dropdown-item" href="{% url 'myinfo:update_post' information.pk %}"> {% endcomment %}
                            <i class="fas fa-edit"></i>
                            編集
                        </a>
                        <a class="dropdown-item" href="{% url 'myinfo:delete' information.pk %}">
                            <i class="fas fa-trash-alt"></i>
                            削除
                        </a>
                    </div>
                </div>
            {% endif %}

        </div>
        <div class="card-body">
            <div class="small">
            {% comment %} <i class="fas fa-paper-plane mr-1"></i>{{ information.to_flag }} {% endcomment %}
            <i class="fas fa-user-edit ml-3 mr-1"></i>{{ information.user }}
            {{ information.created_at }}
            <i class="fas fa-folder-open mr-1"></i>{{ information.category }}
            </div>            

            {% comment %} ↓attachmentモデル逆参照 {% endcomment %}
            {% for each_attachments in information.info_attach.all %}
                <hr>
                {% if '.png' in each_attachments.file_path|stringformat:"s" or '.jpg' in each_attachments.file_path|stringformat:"s" %}
                    <img src = /media/{{ each_attachments.file_path }} />
                {% endif %}
                <i class="fas fa-file"></i>
                <a href="{{ each_attachments.file_path.url }}" target="_blank">
                {% comment %} {{ each_attachments.file_path }} {% endcomment %}
                {{ each_attachments.file_name }}
                </a>
            {% endfor %}

            <hr>
            <div>{{ information.body | safe }}</div>
        </div>
    </div>


    <!-- その日記に紐づいたコメントを取り出す -->
    <p class="m-0">コメント</p>
    
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="small">
                {% for infocomments in information.infocomments_set.all %}
                    {{ infocomments.comment }}
                    <i class="fas fa-user-edit ml-3 mr-1"></i>{{ infocomments.user }}
                    {{ infocomments.created_at }}
                    <hr>
                {% empty %}
                        <p>コメントはありません</p>
                {% endfor %}
            </div>
        </div>
    </div>


    <!-- コメントフォーム -->
    {% if user.is_authenticated %}
        <form action="" method="POST">
            {% csrf_token %}
            <textarea name="text" id="com"  class="form-control"></textarea>

            <div class="d-flex my-3">
                <div class="ml-auto">
                <button type="submit" class="submit btn btn-primary">
                    <i class="fas fa-check"></i> コメントする</button>

                {% comment %} <a class="submit btn btn-primary" href="{% url 'myinfo:comment_post' information.pk %}" role="button">
                    <i class="fas fa-check"></i> コメントする {% endcomment %}
                </a>
            </div>
            </div>
        </form>
    {% else %}
        <p>コメントを書く場合、ログインしてください</p>
    {% endif %}

    <hr>


    <a href="{% url 'myinfo:index' %}" class="btn btn-secondary">一覧</a>
{% endblock %}

myinfo/templates/myinfo/information_list.html
{% extends 'layout.html' %}
{% block content %}

{% if messages %}
		{% for message in messages %}
			<div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
		{% endfor %}
{% endif %}

    {% comment %} <!-- モーダルを開くボタン・リンク -->
    <div class="container">
        <a class="btn btn-primary" data-toggle="modal" data-target="#testModal">削除確認</a>
    </div>
    <!-- ボタン・リンククリック後に表示される画面の内容 -->
    <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">削除確認</h4>
                </div>
                <div class="modal-body">
                    <label>データを削除しますか？</label>
                    <label>{{ information.title }}</label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        <i class="fas fa-chevron-left"></i> 戻る
                    </button>
                    <button type="button" class="btn btn-danger ml-auto" margin-left=auto;>
                        <i class="fas fa-trash-alt"></i> 削除する
                    </button>
                </div>
            </div>
        </div>
    </div> {% endcomment %}

    <!-- 検索フォーム -->
    <div class="d-flex my-3">
    {% if searchForm %}
    <div class="my-box mr-auto">
        <form action='{% url "myinfo:index" %}' method='get'>
            <div class='form-group form-inline'>
                <div class='mr-1'>{{ searchForm.keyword }}</div>
                <input type="submit" class="btn btn-outline-primary mr-1 p-1" value="Search" />
                <a href="{% url 'myinfo:index' %}" class="btn btn-outline-secondary p-1">Clear</a>
            </div>
        </form>
    </div>
    {% endif %}
    
    {% if user.is_authenticated %}
        <div class="ml-auto">
            {% comment %} <a href="{% url 'myinfo:create' %}" class="btn btn-primary"><i class="fas fa-plus"></i> 汎用ビュー</a> {% endcomment %}
            {% comment %} <a href="{% url 'myinfo:add_form' %}" class="btn btn-primary">summernote</a> {% endcomment %}
            {% comment %} <a href="{% url 'myinfo:add_post' %}" class="btn btn-primary">インラインフォームセット</a> {% endcomment %}
            <a href="{% url 'myinfo:add_fbvform' %}" class="btn btn-primary">
            <i class="fas fa-plus"></i> 新規</a>
        </div>
    {% endif %}
    </div>

    {% comment %} {% for information in object_list %} {% endcomment %}{% comment %} #汎用ビュー {% endcomment %}
    {% for information in informations %} {% comment %} #関数ビュー {% endcomment %}
        
        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">

                <!-- タイトル -->
                <h6 class="m-0 font-weight-bold text-primary mr-auto">
                    <!-- 見る側が未読だったら -->
                    {% for unread in unread_set %}
                        {% if information == unread.information and request.user.id == unread.user.id %}
                        <div class="badge badge-info">未読</div>
                        {% endif %}
                    {% endfor %}

                    <a href="{% url 'myinfo:detail' information.pk %}">{{ information.title }}</a>

                </h6>

                <!-- 既読管理：ひとまず未読があったら表示-->
                {% comment %} {% if user.is_superuser %} {% endcomment %}
                {% if request.user.is_staff %}
                    {% for unread in unread_set %}
                        {% if information == unread.information %}
                            <div class="badge badge-warning">{{ unread.user }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}


                <!-- 右側メニュー -->
                {% if request.user.id == information.user.id %}
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">action:</div>
                            <a class="dropdown-item" href="{% url 'myinfo:update' information.pk %}">
                            {% comment %} <a class="dropdown-item" href="{% url 'myinfo:update_post' information.pk %}"> {% endcomment %}
                                <i class="fas fa-edit"></i>
                                編集
                            </a>
                            <a class="dropdown-item" href="{% url 'myinfo:delete' information.pk %}">
                            {% comment %} <a class="dropdown-item" data-toggle="modal" data-target="#testModal"> {% endcomment %}
                                <i class="fas fa-trash-alt"></i>
                                削除
                            </a>
                        </div>
                    </div>

                    <!-- ボタン・リンククリック後に表示される画面の内容 -->
                    <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title " id="myModalLabel">削除の確認</h4>
                                </div>
                                <div class="modal-body">
                                    <label>削除してよろしいですか？（元に戻せません）</label>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                        <i class="fas fa-chevron-left"></i> 戻る
                                    </button>
                                    <button type="button" class="btn btn-danger ml-auto" margin-left=auto;>
                                        <i class="fas fa-trash-alt"></i> 削除する
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endif %}
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="small">{{ information.created_at }}　{{ information.user }}</div>
                <div>{{ information.filefield }}</div>
                <div>
                {{ information.body | striptags | truncatechars_html:50}}
                </div>
            </div>
        </div>

    {% endfor %}


    {% include "pagination.html" %}

    {% comment %} ↑ページネーションのincludeがあたってないので直書き↓ {% endcomment %}
    <ul class="pagination" style="justify-content:center">
    <ul class="pagination">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
    </ul>


    {% comment %} <div class="d-flex my-3">
        <div class="ml-auto">
            <a href="{% url 'myinfo:export' %}" class="btn btn-primary">CSVエクスポート</a>
        </div>
    </div> {% endcomment %}

{% endblock %}