myinfo/urls.py
from django.urls import path
from . import views

app_name = 'myinfo'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('create/', views.CreateView.as_view(), name='create'),
    # path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('add_post', views.add_post, name='add_post'),   # インラインフォームセット
    # path('<int:pk>/update/', views.update_post, name='update_post'),

    path("formview_test", views.aaa.as_view(), name="formview_test"),

    path('export/', views.post_export, name='export'),

    # path('create_comment', views.create_comment, name='create_comment'),   # コメントポスト

    path('fileuptest', views.upload_file, name='fileuptest'),#`ファイルUPテスト用`

    path('', views.information_list, name='index'),   # FBVで一覧
    path('add_fbvform', views.add_fbvform, name='add_fbvform'),   # FBVでCreate
    path('<int:pk>/', views.detail_fbvform, name='detail'),# FBVでDetail
    path('<int:pk>/update/', views.edit_fbvform, name='update'),# FBVでUpdate

    #通知削除関数呼び出し
    path('notifi_delete', views.notifi_delete, name='notifi_delete'),
    
    #添付ファイル削除関数呼び出し
    path('<int:pk>/attach_delete', views.attach_delete, name='attach_delete'),

    # #コメント投稿
    # path('<int:pk>/comment_post', views.comment_post, name='comment_post'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('summernote/', include('django_summernote.urls')),

    path('myinfo/', include('myinfo.urls')),
    path('', RedirectView.as_view(url='/myinfo/')),

]


#     """ 開発環境下のみ設定 """
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/formview_test.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block content %}

{% for error in form.non_field_errors %}
<div class="alert alert-danger">
  {{ error }}
</div>
{% endfor %}

<div class="row">
    <div class="col-sm">
        <h2>変換前</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <p>
                <label>{{ field.label }}</label>
                {{ field }}
            </p>
            {% endfor %}
            <input type="submit" value="変換" class="btn btn-info" />
        </form>  
    </div>
    <div class="col-sm">
        <h2>変換後</h2>
        <p>{{ new_text }}</p>
    </div>
</div>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VCC</title>

    <!-- Custom fonts for this template-->
    <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
    <link href="{% static 'SBadmin2_origin/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <!-- <link href="css/sb-admin-2.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'SBadmin2_origin/css/sb-admin-2.min.css' %}">

    <!-- Custom styles for this page -->
    <link href="{% static 'SBadmin2_origin/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

   <!-- ウィジェットのcssとjs -->
   <link href="{% static 'accordion.css' %}" rel="stylesheet">
   <script src="{% static 'accordion.js' %}"></script>
   
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href='{% url "myinfo:index" %}'>
                <div class="sidebar-brand-text mx-3">VCC MARSH</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href='{% url "myinfo:index" %}'>
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>おしらせ</span></a>
            </li>

            {% comment %} <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="buttons.html">Buttons</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li> {% endcomment %}


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Alerts -->
                        {% comment %} <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link" href="{% url 'myinfo:notifi_delete' %}" role="button">
                            <i class="fas fa-bell fa-fw"></i>
                            <!-- Counter - Alerts -->
                            {% if notifi_exis == True %}
                                <span class="badge badge-danger badge-counter">通知があります</span>
                            {% endif %}
                            </a>
                        </li> {% endcomment %}

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="text-gray-600 d-flex align-items-center">
                            {% if user.is_authenticated %}
                                    <div>{{ user.last_name }}　</div>
                                    <a href='{% url "logout" %}' class="nav-link">
                                        <i class="fas fa-sign-out-alt"></i>
                                    </a>
                            {% else %}
                                <a href='{% url "login" %}' class="nav-link">Login</a>
                            {% endif %}
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <!-- <h1 class="h3 mb-4 text-gray-800">Blank Page</h1> -->


                    <div class='container'>
                        {% block content %}
                        {% endblock %}
                    </div>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; VccMarsh 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'SBadmin2_origin/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'SBadmin2_origin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'SBadmin2_origin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'SBadmin2_origin/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'SBadmin2_origin/vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'SBadmin2_origin/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'SBadmin2_origin/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'SBadmin2_origin/js/demo/chart-pie-demo.js' %}"></script>
    <script src="{% static 'SBadmin2_origin/js/demo/datatables-demo.js' %}"></script>


</body>

</html>

templates/pagination.html
<!--
 is_paginatedは表示結果がページ分割されているかどうかを示すブール値
 オブジェクトの個数が paginate_by と等しいか
 それ以下の場合には False にセットされる
-->
{% if is_paginated %}
  <!-- 左右の中央に配置 -->
  <ul class="pagination" style="justify-content:center">
    <!--
     前ページへのリンク
     Page.has_previous: 前のページがある場合に True を返します
    -->
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link"
        href="?page={{ page_obj.previous_page_number }}"
        aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    <!--
     ページ数の表示
     paginator.page_range: [1, 2, 3, 4] のように、 1 から始まるページ番号
    -->
    {% for num in paginator.page_range %}
      <!--
       ページ番号が存在しない場合
       Page.number: 1から数えたページ番号
      -->
      {% if page_obj.number == num %}
        <li class="page-item active">
          <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}
    <!--
     次ページへのリンク
     Page.next_page_number: 次のページがある場合にTrueを返す
     -->
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}